[package]
name = "Ferrisyum"
version = "0.1.0"
authors = ["Zach Meyer <zach.meyer@outlook.com>"]
license = "WTFPL"
edition = "2024"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.28.1"
grid = "0.16.1"
nalgebra = "0.33.2"
ratatui = "0.29.0"
regex = "1.11.1"
